In [7]:
import numpy as np

def gram_schmidt_qr(A):
    """
    Realiza la descomposición QR de una matriz A usando Gram-Schmidt clásico.
    A = Q * R
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    # Iteramos sobre cada columna de A
    for j in range(n):
        v = A[:, j].astype(float) # Obtenemos la columna j como vector

        # Restamos las proyecciones de los vectores Q anteriores
        for i in range(j):
            # R[i, j] es el producto punto: q_i . a_j
            R[i, j] = np.dot(Q[:, i], A[:, j])
            # Restamos la proyección: v = v - (r_ij * q_i)
            v = v - R[i, j] * Q[:, i]

        # Calculamos la norma (magnitud) del vector resultante
        norma = np.linalg.norm(v)
        R[j, j] = norma
        
        # Normalizamos para obtener la columna j de Q
        # Manejo de error si la norma es muy pequeña (división por cero)
        if norma > 1e-10:
            Q[:, j] = v / norma
        else:
            Q[:, j] = 0

    return Q, R

def calcular_eigenvalores_qr(A, iteraciones=100):
    """
    Calcula los eigenvalores usando la iteración QR.
    Repite A_k+1 = R_k * Q_k hasta converger.
    """
    A_k = A.copy()
    
    print(f"--- Iniciando Iteraciones ({iteraciones}) ---")
    
    for i in range(iteraciones):
        # 1. Descomponer A en Q y R
        Q, R = gram_schmidt_qr(A_k)
        
        # 2. Multiplicar en orden inverso: A_new = R * Q
        A_k = np.dot(R, Q)
        
        # Opcional: Imprimir el progreso de la diagonal en las primeras iteraciones
        if i < 5: 
            print(f"Iteración {i+1}: {np.diag(A_k)}")

    # Los eigenvalores se encuentran en la diagonal principal
    return np.diag(A_k)

# --- EJEMPLO DE USO ---

# Definimos una matriz simétrica (garantiza eigenvalores reales)
matriz_datos = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])

print("Matriz Original:")
print(matriz_datos)
print()

# Ejecutamos nuestro algoritmo manual
eigenvalores = calcular_eigenvalores_qr(matriz_datos)

print("\nResultados Finales:")
print(f"Eigenvalores calculados (Python Manual): {eigenvalores}")

# Comparación con la función nativa de NumPy (para validación)
eigen_numpy = np.linalg.eigvals(matriz_datos)
print(f"Eigenvalores NumPy (Referencia):      {eigen_numpy}")
print(np.linalg.eig(matriz_datos)[1])

Matriz Original:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

--- Iniciando Iteraciones (100) ---
Iteración 1: [15.27272727 -0.27272727  0.        ]
Iteración 2: [16.15862069 -1.15862069  0.        ]
Iteración 3: [16.11385786 -1.11385786  0.        ]
Iteración 4: [16.11705046 -1.11705046  0.        ]
Iteración 5: [16.11682966 -1.11682966  0.        ]

Resultados Finales:
Eigenvalores calculados (Python Manual): [16.11684397 -1.11684397  0.        ]
Eigenvalores NumPy (Referencia):      [ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
