In [3]:
import numpy as np

def gram_schmidt_qr(A):
    """
    Realiza la descomposición QR de una matriz A usando Gram-Schmidt clásico.
    A = Q * R
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    # Iteramos sobre cada columna de A
    for j in range(n):
        v = A[:, j].astype(float) # Obtenemos la columna j como vector

        # Restamos las proyecciones de los vectores Q anteriores
        for i in range(j):
            # R[i, j] es el producto punto: q_i . a_j
            R[i, j] = np.dot(Q[:, i], A[:, j])
            # Restamos la proyección: v = v - (r_ij * q_i)
            v = v - R[i, j] * Q[:, i]

        # Calculamos la norma (magnitud) del vector resultante
        norma = np.linalg.norm(v)
        R[j, j] = norma
        
        # Normalizamos para obtener la columna j de Q
        # Manejo de error si la norma es muy pequeña (división por cero)
        if norma > 1e-10:
            Q[:, j] = v / norma
        else:
            Q[:, j] = 0

    return Q, R

def calcular_eigenvalores_qr(A, iteraciones=100):
    """
    Calcula los eigenvalores usando la iteración QR.
    Repite A_k+1 = R_k * Q_k hasta converger.
    """
    A_k = A.copy()
    
    print(f"--- Iniciando Iteraciones ({iteraciones}) ---")
    
    for i in range(iteraciones):
        # 1. Descomponer A en Q y R
        Q, R = gram_schmidt_qr(A_k)
        
        # 2. Multiplicar en orden inverso: A_new = R * Q
        A_k = np.dot(R, Q)
        
        # Opcional: Imprimir el progreso de la diagonal en las primeras iteraciones
        if i < 5: 
            print(f"Iteración {i+1}: {np.diag(A_k)}")

    # Los eigenvalores se encuentran en la diagonal principal
    return np.diag(A_k)

# --- EJEMPLO DE USO ---

# Definimos una matriz simétrica (garantiza eigenvalores reales)
matriz_datos = np.array([
    [4.0, 1.0, -2.0],
    [1.0, 2.0, 0.0],
    [-2.0, 0.0, 3.0]
])

print("Matriz Original:")
print(matriz_datos)
print()

# Ejecutamos nuestro algoritmo manual
eigenvalores = calcular_eigenvalores_qr(matriz_datos)

print("\nResultados Finales:")
print(f"Eigenvalores calculados (Python Manual): {eigenvalores}")

# Comparación con la función nativa de NumPy (para validación)
eigen_numpy = np.linalg.eigvals(matriz_datos)
print(f"Eigenvalores NumPy (Referencia):      {eigen_numpy}")

Matriz Original:
[[ 4.  1. -2.]
 [ 1.  2.  0.]
 [-2.  0.  3.]]

--- Iniciando Iteraciones (100) ---
Iteración 1: [5.61904762 2.0621118  1.31884058]
Iteración 2: [5.72362556 2.22601546 1.05035898]
Iteración 3: [5.73102542 2.25959282 1.00938176]
Iteración 4: [5.73189926 2.26628778 1.00181296]
Iteración 5: [5.73202736 2.26762043 1.00035221]

Resultados Finales:
Eigenvalores calculados (Python Manual): [5.73205081 2.26794919 1.        ]
Eigenvalores NumPy (Referencia):      [5.73205081 1.         2.26794919]
